# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class DeleteAgentAssetResponseData(UniversalBaseModel):
    asset_id: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="assetId")] = pydantic.Field(
        default=None
    )
    """
    ID of the deleted asset
    """

    chunks_removed: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="chunksRemoved")] = (
        pydantic.Field(default=None)
    )
    """
    Number of text chunks removed from search database
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
