# This file was auto-generated by Fern from our API Definition.

import typing

AgentConfigurationTtsModel = typing.Union[
    typing.Literal["Eleven-turbo-v2-5", "Eleven-turbo-v2", "Eleven-multilingual-v2"], typing.Any
]
