# This file was auto-generated by Fern from our API Definition.

import typing

AgentConfigurationLlmModel = typing.Union[
    typing.Literal["gpt-4o-mini", "gpt-4o", "gpt-3.5-turbo", "claude-3-sonnet", "claude-3-haiku", "gemini-pro"],
    typing.Any,
]
