# This file was auto-generated by Fern from our API Definition.

import typing

AgentConfigurationStructuredDataSchemaCallType = typing.Union[
    typing.Literal["Reservation", "Takeaway", "Delivery", "Walk-in", "Enquiry", "Information", "Other"], typing.Any
]
