# This file was auto-generated by Fern from our API Definition.

import typing

AnthropicLlmModel = typing.Union[
    typing.Literal[
        "claude-3-opus-20240229",
        "claude-3-sonnet-20240229",
        "claude-3-haiku-20240307",
        "claude-3-5-sonnet-20240620",
        "claude-3-5-sonnet-20241022",
        "claude-3-5-haiku-20241022",
        "claude-3-7-sonnet-20250219",
        "claude-opus-4-20250514",
        "claude-sonnet-4-20250514",
    ],
    typing.Any,
]
