# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CoreCallResponseDataCallTracking(UniversalBaseModel):
    call_id: typing.Optional[str] = None
    agent_id: typing.Optional[str] = None
    to_number: typing.Optional[str] = None
    initiated_at: typing.Optional[dt.datetime] = None
    estimated_credits: typing.Optional[int] = None
    available_credits: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
