# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .core_call_response_data_call_tracking import CoreCallResponseDataCallTracking


class CoreCallResponseData(UniversalBaseModel):
    core_response: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = None
    call_tracking: typing.Optional[CoreCallResponseDataCallTracking] = None
    status_code: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
