# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class LoginResponseDataTokens(UniversalBaseModel):
    jwt: typing.Optional[str] = pydantic.Field(default=None)
    """
    JWT token for API access
    """

    firebase: typing.Optional[str] = pydantic.Field(default=None)
    """
    Firebase token
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
