# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .organization_membership_role import OrganizationMembershipRole
from .organization_membership_subscription_status import OrganizationMembershipSubscriptionStatus


class OrganizationMembership(UniversalBaseModel):
    id: typing.Optional[int] = None
    name: typing.Optional[str] = None
    subscription_status: typing.Optional[OrganizationMembershipSubscriptionStatus] = None
    credits_balance: typing.Optional[int] = None
    role: typing.Optional[OrganizationMembershipRole] = pydantic.Field(default=None)
    """
    User's role in this organization
    """

    is_default: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether this is the user's primary organization
    """

    joined_at: typing.Optional[dt.datetime] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
