# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class Organization(UniversalBaseModel):
    pk_org_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    Organization ID
    """

    org_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Organization name
    """

    org_email: typing.Optional[str] = None
    org_address: typing.Optional[str] = None
    tax_id: typing.Optional[str] = None
    is_active: typing.Optional[bool] = None
    created_at: typing.Optional[dt.datetime] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
