# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .organization import Organization
from .organization_detailed_subscription_status import OrganizationDetailedSubscriptionStatus
from .organization_member import OrganizationMember
from .organization_stats import OrganizationStats


class OrganizationDetailed(Organization):
    subscription_status: typing.Optional[OrganizationDetailedSubscriptionStatus] = pydantic.Field(default=None)
    """
    Current subscription tier
    """

    credits_balance: typing.Optional[int] = pydantic.Field(default=None)
    """
    Available credits (in seconds of call time)
    """

    members: typing.Optional[typing.List[OrganizationMember]] = None
    stats: typing.Optional[OrganizationStats] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
