# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .organization_member_role import OrganizationMemberRole


class OrganizationMember(UniversalBaseModel):
    pk_user_id: typing.Optional[int] = None
    email: typing.Optional[str] = None
    name: typing.Optional[str] = None
    is_active: typing.Optional[bool] = None
    role: typing.Optional[OrganizationMemberRole] = None
    joined_at: typing.Optional[dt.datetime] = None
    is_default_org: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether this organization is the user's primary org
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
