# This file was auto-generated by Fern from our API Definition.

import typing

ToolParameterParamType = typing.Union[
    typing.Literal["string", "integer", "number", "boolean", "array", "object"], typing.Any
]
