# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .organization_membership import OrganizationMembership


class UserOrganizationsResponseData(UniversalBaseModel):
    user_id: typing.Optional[int] = None
    default_org_id: typing.Optional[int] = None
    organizations: typing.Optional[typing.List[OrganizationMembership]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
